HW1 - ‘Змінні, типи даних та оператори’
maksym-dragomirov/prjctr-js12 pull request #1
Opened 2024-04-14 21:21 UTC by maksym-dragomirov

2024-04-15 15:52 UTC, myroslav-kolomiiets requested changes

2024-04-15 15:52 UTC, myroslav-kolomiiets commented on homeworks/hw1.js
> +let x = 5;
Ця і подальші змінні не перезаписується в подальшому виконанні скрипта, тому їх треба об'являти як константи.
```suggestion
const x = 5;
```
і так з наступними

2024-04-15 15:52 UTC, myroslav-kolomiiets commented on homeworks/hw1.js
> +console.log('Додавання: ' + addition);
Тут можна використати сучасніший синтаксис і записати так
```suggestion
console.log(`Додавання:  ${addition}`);
```

2024-04-15 21:41 UTC, maksym-dragomirov commented on homeworks/hw1.js
> +let x = 5;
Updated.

2024-04-15 21:41 UTC, maksym-dragomirov commented on homeworks/hw1.js
> +console.log('Додавання: ' + addition);
Updated.

2024-04-16 09:22 UTC, myroslav-kolomiiets approved these changes

2024-04-24 16:53 UTC, merged