HW10 - "Основи роботи з DOM - атрибути, властивості, події"
maksym-dragomirov/prjctr-js12 pull request #12
Opened 2024-06-02 15:47 UTC by maksym-dragomirov

2024-06-05 20:20 UTC, myroslav-kolomiiets requested changes

2024-06-05 20:20 UTC, myroslav-kolomiiets commented on homeworks/hw10.js
> +(() => {
Якщо використовувати IIFE то краще обгорнути і все решта в неї, інакше змінні в глобальній області все рівно

2024-06-05 20:20 UTC, myroslav-kolomiiets commented on homeworks/hw10.js
> +        pageBody.style.backgroundColor = '#2F2222';
Краще оперувати css класами, а не задавати стилі напряму

2024-06-05 20:20 UTC, myroslav-kolomiiets commented on homeworks/hw10.js
> +    if (currentTime === 0 || currentTime === null) {
так на 6 рядку якщо localStorage.getItem не знайде по ключу данні і поверне null, в тебе в змінну currentTime запишеться 0, то навіщо ця перевірка і на 0 і на null?

2024-06-05 20:20 UTC, myroslav-kolomiiets commented on homeworks/hw10.js
> +        pageBody.style.backgroundColor = '#2F2222';
Краще всі стилі задавати через css класи, тому що навіть зараз це вже не дуже зручно читати, а якщо треба буде ще більше? Тому classList в допомогу)

2024-06-09 15:08 UTC, maksym-dragomirov commented on homeworks/hw10.js
> +(() => {
Оновив, забрав IIFE, оскільки працює і без цього.

2024-06-09 15:09 UTC, maksym-dragomirov commented on homeworks/hw10.js
> +        pageBody.style.backgroundColor = '#2F2222';
Оновив, створив додаткові класи на кольори сторінки та тексту.

2024-06-17 20:02 UTC, myroslav-kolomiiets approved these changes

2024-06-17 20:18 UTC, merged